var regions=new Array();
regions[0]=new Option("","");
regions[1]=new Option("Africa","comboAfrica");
regions[2]=new Option("Asia","comboAsia");
regions[3]=new Option("Europa", "comboEuropa");
regions[4]=new Option("Latinoamerica","comboLatamAmerica");
regions[5]=new Option("Norte America","comboNorteAmerica");
regions[6]=new Option("Oceania","comboOceania");


var comboLatamAmerica=new Array();
comboLatamAmerica[0]=new Option("","");
comboLatamAmerica[1]=new Option("Argentina","Argentina");
comboLatamAmerica[2]=new Option("Brasil","Brasil");
comboLatamAmerica[3]=new Option("Bolivia","Bolivia");
comboLatamAmerica[4]=new Option("Chile","Chile");
comboLatamAmerica[5]=new Option("Colombia","Colombia");
comboLatamAmerica[6]=new Option("Costa Rica","Costa Rica");
comboLatamAmerica[7]=new Option("Ecuador","Ecuador");
comboLatamAmerica[8]=new Option("El Salvador","El Salvador");
comboLatamAmerica[9]=new Option("Guatemala","Guatemala");
comboLatamAmerica[10]=new Option("Haiti","Haiti");
comboLatamAmerica[11]=new Option("Honduras","Honduras");
comboLatamAmerica[12]=new Option("Jamaica","Jamaica");
comboLatamAmerica[13]=new Option("México","MX");
comboLatamAmerica[14]=new Option("Nicaragua","Nicaragua");
comboLatamAmerica[15]=new Option("Panamá","Panamá");
comboLatamAmerica[16]=new Option("Paraguay","Paraguay");
comboLatamAmerica[17]=new Option("Perú","Perú");
comboLatamAmerica[18]=new Option("Republica Dominicana","Republica Dominicana");
comboLatamAmerica[19]=new Option("Uruguay","Uruguay");
comboLatamAmerica[20]=new Option("Venezuela","Venezuela");

var comboNorteAmerica=new Array();
comboNorteAmerica[0]=new Option("","");
comboNorteAmerica[1]=new Option("Estados Unidos","Estados Unidos");
comboNorteAmerica[2]=new Option("Canada","Canada");

var comboEuropa=new Array();
comboEuropa[0]=new Option("","");
comboEuropa[1]=new Option("Alemania","Alemania");
comboEuropa[2]=new Option("Austria","Austria");
comboEuropa[3]=new Option("Bélgica","Bélgica");
comboEuropa[4]=new Option("Bulgaria","Bulgaria");
comboEuropa[5]=new Option("Crocacia","Crocacia");
comboEuropa[6]=new Option("Dinamarca","Dinamarca");
comboEuropa[7]=new Option("Eslovaquia","Eslovaquia");
comboEuropa[8]=new Option("Eslovenia","Eslovenia");
comboEuropa[9]=new Option("España","España");
comboEuropa[10]=new Option("Estonia","Estonia");
comboEuropa[11]=new Option("Finlandia","Finlandia");
comboEuropa[12]=new Option("Francia","Francia");
comboEuropa[13]=new Option("Grecia","Grecia");
comboEuropa[14]=new Option("Holanda","Holanda");
comboEuropa[15]=new Option("Hungría","Hungría");
comboEuropa[16]=new Option("Irlanda","Irlanda");
comboEuropa[17]=new Option("Letonia","Letonia");
comboEuropa[18]=new Option("Lituania","Lituania");
comboEuropa[19]=new Option("Luxemburgo","Luxemburgo");
comboEuropa[20]=new Option("Malta","Malta");
comboEuropa[21]=new Option("Noruega","Noruega");
comboEuropa[22]=new Option("Polonia","Polonia");
comboEuropa[23]=new Option("Portugal","Portugal");
comboEuropa[24]=new Option("Reino Unido","Reino Unido");
comboEuropa[25]=new Option("Republica Checa","Republica Checa");
comboEuropa[26]=new Option("Rumania","Rumania");
comboEuropa[27]=new Option("Rusia","Rusia");
comboEuropa[28]=new Option("Suecia","Suecia");
comboEuropa[29]=new Option("Ucrania","Ucrania");


var comboAsia=new Array();
comboAsia[0]=new Option("","");
comboAsia[1]=new Option("Afganistan","Afganistan");
comboAsia[2]=new Option("Arabia Saudita","Arabia Saudita");
comboAsia[3]=new Option("Armenia","Armenia");
comboAsia[4]=new Option("Afganistan","Afganistan");
comboAsia[5]=new Option("Bahrein","Bahrein");
comboAsia[6]=new Option("Bangladesh","Bangladesh");
comboAsia[7]=new Option("Birmania","Birmania");
comboAsia[8]=new Option("Brunei","Brunei");
comboAsia[9]=new Option("Butan","Butan");
comboAsia[10]=new Option("Camboya","Camboya");
comboAsia[11]=new Option("China","China");
comboAsia[12]=new Option("Corea del Norte","Corea del Norte");
comboAsia[13]=new Option("Corea del Sur","Corea del Sur");
comboAsia[14]=new Option("Emiratos Arabes","Emiratos Arabes");
comboAsia[15]=new Option("Filipinas","Filipinas");
comboAsia[16]=new Option("Georgias","Georgias");
comboAsia[17]=new Option("India","India");
comboAsia[18]=new Option("Indonesia","Indonesia");
comboAsia[19]=new Option("Iraq","Iraq");
comboAsia[20]=new Option("Iran","Iran");
comboAsia[21]=new Option("Israel","Israel");
comboAsia[22]=new Option("Japon","Japon");
comboAsia[23]=new Option("Jordania","Jordania");
comboAsia[24]=new Option("Kazajistan","Kazajistan");
comboAsia[25]=new Option("Kuwait","Kuwait");
comboAsia[26]=new Option("Laos","Laos");
comboAsia[27]=new Option("Libano","Libano");
comboAsia[28]=new Option("Malasia","Malasia");
comboAsia[29]=new Option("Maldivas","Maldivas");
comboAsia[30]=new Option("Mongolia","Mongolia");
comboAsia[31]=new Option("Nepal","Nepal");
comboAsia[32]=new Option("Oman","Oman");
comboAsia[33]=new Option("Pakistan","Pakistan");
comboAsia[34]=new Option("Qatar","Qatar");
comboAsia[35]=new Option("Singapur","Singapur");
comboAsia[36]=new Option("Siria","Siria");
comboAsia[37]=new Option("Sri Lanka","Sri Lanka");
comboAsia[38]=new Option("Tailandia","Tailandia");
comboAsia[39]=new Option("Taiwan","Taiwan");
comboAsia[40]=new Option("Turquia","Turquia");
comboAsia[41]=new Option("Uzbekistan","Uzbekistan");
comboAsia[42]=new Option("Vietnam","Vietnam");
comboAsia[43]=new Option("Yemen","Yemen");

var comboOceania=new Array();
comboOceania[0]=new Option("","");
comboOceania[1]=new Option("Australia","Australia");
comboOceania[2]=new Option("Nueva Zelanda","Nueva Zelanda");

var comboAfrica=new Array();
comboAfrica[0]=new Option("","");
comboAfrica[1]=new Option("Angola","Angola");
comboAfrica[2]=new Option("Argelia","Argelia");
comboAfrica[3]=new Option("Botswana","Botswana");
comboAfrica[4]=new Option("Burkina-Fasso","Burkina-Fasso");
comboAfrica[5]=new Option("Burundi","Burundi");
comboAfrica[6]=new Option("Cabo Verde","Cabo Verde");
comboAfrica[7]=new Option("Camerun","Camerun");
comboAfrica[8]=new Option("Costa de Marfil","Costa de Marfil");
comboAfrica[9]=new Option("Egipto","Egipto");
comboAfrica[10]=new Option("Etiopia","Etiopia");
comboAfrica[11]=new Option("Gabon","Gabon");
comboAfrica[12]=new Option("Gambia","Gambia");
comboAfrica[13]=new Option("Ghana","Ghana");
comboAfrica[14]=new Option("Guinea","Guinea");
comboAfrica[15]=new Option("Kenya","Kenya");
comboAfrica[16]=new Option("Libia","Libia");
comboAfrica[17]=new Option("Madagascar","Madagascar");
comboAfrica[18]=new Option("Malawi","Malawi");
comboAfrica[19]=new Option("Mali","Mali");
comboAfrica[20]=new Option("Marruecos","Marruecos");
comboAfrica[21]=new Option("Mozambique","Mozambique");
comboAfrica[22]=new Option("Namibia","Namibia");
comboAfrica[23]=new Option("Niger","Niger");
comboAfrica[24]=new Option("Nigeria","Nigeria");
comboAfrica[25]=new Option("Rwanda","Rwanda");
comboAfrica[26]=new Option("Sahara","Sahara");
comboAfrica[27]=new Option("Senegal","Senegal");
comboAfrica[28]=new Option("Somalia","Somalia");
comboAfrica[29]=new Option("Sudafrica","Sudafrica");
comboAfrica[30]=new Option("Sudan","Sudan");
comboAfrica[31]=new Option("Tanzania","Tanzania");
comboAfrica[32]=new Option("Togo","Togo");
comboAfrica[33]=new Option("Tunez","Tunez");
comboAfrica[34]=new Option("Uganda","Uganda");
comboAfrica[35]=new Option("Zambia","Zambia");
comboAfrica[36]=new Option("Zimbabwe","Zimbabwe");
	
function populate(x){
	var regionCombo=document.getElementById('region');
	var countryCombo=document.getElementById('country');
	if(regionCombo.selectedIndex==0) {
		countryCombo.length=0;
		return;
	}
		var selectedarray=eval(x)
		countryCombo.length=0;
		for (i=0;i<selectedarray.length;i++)
			countryCombo.options[i]=new Option(selectedarray[i].text,selectedarray[i].value)
		countryCombo.options[0].selected=true

}